# Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

In [ ]:
import pandas as pd

### CSV Input syntax

In [ ]:
customers_url="https://raw.githubusercontent.com/ShilpaSayuraML/Python-for-Finance/master/Chapter%202/Pandas/Customers.csv"
dataframe = pd.read_csv(customers_url)

### CSV Output returned

In [ ]:
dataframe.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
type(dataframe)

pandas.core.frame.DataFrame

In [ ]:
dataframe.to_csv('customer_copy.csv',index=False)

## Excel
Pandas is able to read and write from and in a excel file

### Excel Input

In [6]:
import pandas as pd
import requests

In [4]:
excel_url='https://github.com/ShilpaSayuraML/Python-for-Finance/blob/master/Chapter%202/Pandas/Sample.xlsx'
df=pd.read_excel(excel,sheet_name='Sample')
df.head()

ValueError: ignored

In [ ]:
type(df)

pandas.core.frame.DataFrame

### Excel Output

In [ ]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

## HTML

Pandas can read table from the html.

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [ ]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
df[0].head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Washington Federal Bank for Savings,Chicago,IL,30570,Royal Savings Bank,"December 15, 2017","February 21, 2018"
1,The Farmers and Merchants State Bank of Argonia,Argonia,KS,17719,Conway Bank,"October 13, 2017","February 21, 2018"
2,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb","May 26, 2017","July 26, 2017"
3,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,"May 5, 2017","March 22, 2018"
4,First NBC Bank,New Orleans,LA,58302,Whitney Bank,"April 28, 2017","December 5, 2017"